### PR TITLE
fix(sem): sigmatch matches check for errors before updating call node

### PR DESCRIPTION
**Pull request by saem**
## Summary
* what changed and how?
* why are we changing it?

## Details
* info that couldn't fit into the summary
* relevant details; tricky parts
* anything else

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

### CODE REVIEW

**Comment by zerbina** [comment]
Ah, so it's the known "template/macro with `untyped` parameter has overloads with typed parameter" problem. A reduced test case:
```nim
# ``test`` has to be an overloaded routine, where the overload with the non-
# untyped parameter has to be defined **first**

proc test(arg: string) =
  discard

template test(arg: untyped) =
  for it in arg:
    discard

# two overloads of ``test2`` have to exist, with one being an iterator while
# the other is not. The return types don't matter as long as the non-iterator
# doesn't return anything that matches `string` or something for which an
# ``items`` iterator exists.
iterator test2(): int =
  yield 0

proc test2(): bool =
  discard

test(test2())
```

**Comment by saem** [comment]
Current minimal case to reproduce the existing issue:

```nim
type
  Foo = enum
    foo1
    foo2
    foo3

const someFoos = {foo2 .. foo3}

doAssert set[Foo](someFoos) == {foo2, foo3}
```

**Comment by saem** [comment]
Minor update: That took a long while, but the issue is starting to become more clear. `matchesAux`'s `noMatchAux` template, which is used to signal errors, relies on `n`, the call's input AST, to contain the call arg, which is not the case after this change. This proc is likely going to require a fair bit of refactoring to get this to work properly.

**Comment by saem** [comment]
This PR has been superceded by this one: https://github.com/nim-works/nimskull/pull/1102

**Pull request closed without merging**
