### PR TITLE
move discard, let, rationals to stmts/stdlib categories

### PR DESCRIPTION
**Pull request by haxscramper**

### CODE REVIEW

**Review by saem — CHANGES_REQUESTED** [review]
Wait, why is there a binary added?

**Comment by haxscramper** [comment]
ah right I guess that's why it fails, I somehow missed it

**Comment by saem** [comment]
Can you check to see if binaries got added in other recent changes to tests you've made?

**Comment by haxscramper** [comment]
there are no binaries in previous PRs

**Review by saem — APPROVED** [review]

**Comment by haxscramper** [comment]
bors  r+

**Pull request merged**
