### PR TITLE
Implement shell command runner wrapper

### LINKED ISSUE #213: Move away from the `string` for handling executed commands
Most of the commands executed in the compiler go through the `execProcesses*(cmds: openArray[string],` or `execCmdEx*(command: string,` and as a consequence, most of the code handles strings by immediately joining them, using string template interpolation all over the place. While by itself it is not *too* bad, it makes it harder to reason about the code, because semi-random string joins all over the place, like 

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/compiler/backend/extccomp.nim#L357-L359

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/compiler/backend/extccomp.nim#L491-L492

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/compiler/backend/extccomp.nim#L539

As well as weird handling of the shell execution results, where (again), premature string formatting completely conceals the purpose and *data flow* in the code.

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/testament/testament.nim#L474

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/testament/specs.nim#L120-L124

https://github.com/nim-works/nimskull/blob/afbd5fe6fb4882d2094069b53a877cc1997f3a32/testament/testament.nim#L179-L187

Instead, several helper types should be introduced to abstract away the command handling logic - `ShellCmd`, `ShellResult`, `ShellCmdPart`. 

https://github.com/nim-works/nimskull/blob/829ffa1fb6a557bd7e65485383273bafcbde2378/compiler/front/main.nim#L84-L93

https://github.com/nim-works/nimskull/blob/829ffa1fb6a557bd7e65485383273bafcbde2378/compiler/backend/extccomp.nim#L416-L418

https://github.com/nim-works/nimskull/blob/829ffa1fb6a557bd7e65485383273bafcbde2378/compiler/backend/extccomp.nim#L235-L240

https://github.com/nim-works/nimskull/blob/829ffa1fb6a557bd7e65485383273bafcbde2378/compiler/backend/extccomp.nim#L112

### PR DESCRIPTION
**Pull request by haxscramper**
Closes https://github.com/nim-works/nimskull/issues/213

### CODE REVIEW

**Comment by saem** [comment]
I know this was a bear in terms of discussion, consider this PR/commit message my peace offering and thank you!

```
Implement shell command runner wrapper

Most of the commands executed in the compiler go through
`execProcesses*(cmds: openArray[string], ...)`, or
`execCmdEx*(command: string, ...)` and as a consequence, most of the code
handles strings by immediately joining them. Leading to the usage of string
template interpolation all over the place.

While by itself it is not too bad, it makes it harder to reason about the code,
because semi-random string joins, potentially escaped (or forgotten), and
perhaps used in a hastily put together string interpolation system.

Closes nim-works#213

see: https://github.com/nim-works/nimskull/issues/213
```

There is one suggestion for module docs, but good with a bors thereafter.

**Comment by haxscramper** [comment]
```

Closes nim-works#213

see: https://github.com/nim-works/nimskull/issues/213
```

pointless separation - why link the same thing twice? Auto-closing works with standalone URLs, that's why there is no reason to only link commit hashes. Also why this is a `nim-works#213` instead of `nimskull#213`

**Comment by saem** [comment]
> ```
> 
> Closes nim-works#213
> 
> see: https://github.com/nim-works/nimskull/issues/213
> ```
> 
> pointless separation - why link the same thing twice? Auto-closing works with standalone URLs, that's why there is no reason to only link commit hashes. Also why this is a `nim-works#213` instead of `nimskull#213`

No clue, that was the original PR body so wasn't sure if it was a must. I kept both in case.

**Pull request merged**
