### PR TITLE
cgen: minor code cleanup

### PR DESCRIPTION
**Pull request by iacore**
Removed unnecessary forward declaration and fixed code formatting, no change in behaviour.

### CODE REVIEW

**Comment by saem** [comment]
Updated the PR description, rather than going into all the types of things a PR/commit message should contain, I thought this would be easier to see via example. @iacore if you're fine with the message as it is or after you've made any further edits let me know and I'll merge queue this for merge.

Thanks again for the PR. ❤️

**Comment by iacore** [comment]
It's fine. You can merge it. I'll write better PR message next time.

**Comment by iacore** [comment]
What is this bot shenanigans

Is the PR title used too?

**Comment by saem** [comment]
Yes the title and everything before the horizontal rule become the commit message. The stuff after the horizontal rule is a space to communicate meta-pr stuff that doesn't fit in the commit message like notes to reviewers. The PR template has some inline explanation of all this. Which also means pr messages need hard line wrapping.

We treat the PR body/commit message as change log entries. So no overly terse tithes and bodies, instead explain what, why, how, etc for others on the project or those looking to learn etc. It's more thoroughly covered in the contribution guide.

**Pull request merged**
