### PR TITLE
Ambsym

### PR DESCRIPTION
**Pull request by canelhasmateus**
More illustrative and detailed examples for the `ambsym`
category. We also add labels and descriptions for the
`actiontable` , `alias` , and `align` categories.

This is part of a bigger effort, see
https://github.com/nim-works/nimskull/issues/41

### CODE REVIEW

**Comment by canelhasmateus** [comment]
I think that ambsym is a suboptimal name.
IMHO, `identifier resolution` is a better name.

**Comment by saem** [comment]
> I think that ambsym is a suboptimal name. IMHO, `identifier resolution` is a better name.

The original intention was `ambiguous symbol(s)`, which is perhaps better in that this doesn't look at all aspects of identifier resolution.

**Comment by canelhasmateus** [comment]
how about a nice compromise in `symbol resolution`?

**Comment by saem** [comment]
sure, it doesn't take much to beat `ambsym`

**Comment by saem** [comment]
bors r+

thanks

**Pull request merged**
