### PR TITLE
Clean up `stdlib` test category

### PR DESCRIPTION
**Pull request by haxscramper**
- Create  additional  subdirectories  for   the  standard  library  testing
  category. Instead of a  giant mess with over a hundred  files in the same
  directory it  is now split into  several smaller pieces. Other  test that
  /should/ be in the stdlib category  have not been moved, TODO for another
  PR.
- Add  `"cache"`   command  that  was   missing  from  the   testament:  it
  was  *impossible* to  run  a single  category and  then  retry it  again,
  because `cacheResults()` was only called at the end of `all` (which takes
  a lot more time to run).
- Newly  introduced directories  in  the stdlib  category have  `readme.md`
  attached to them.

Future directions:

- there  are  several completely  useless  categories  along the  lines  of `tactiontable.nim` (I can't even fathom how someone thought it might be a good idea to place this into a separate category) and others that need to be moved to the `stdlib`.
- Provide documentation  on the  end-to-end process  of placing  tests into appropriate directories.
- Start   rearranging   internal   stdlib   tests   `tstdlib_various`   and
  `tstdlib_issues` are absolutely revulsing and should be organized.

Smaller version of https://github.com/nim-works/nimskull/pull/455

### CODE REVIEW

**Comment by haxscramper** [comment]
Single test failing

```nim
FAIL: tests/stdlib/nre/tnre.nim c                                  ( 1.05 sec)
Test "tests/stdlib/nre/tnre.nim" in category "stdlib"
Failure: reNimcCrash
$ /mnt/workspace/repos/nimskull/bin/nim c --hints:on -d:testing --clearNimblePath --nimblePath:build/deps/pkgs   --nimCache:nimcache/tests/stdlib/nre/tnre.nim_4a8a08f09d37b73795649038408b5f33  tests/stdlib/nre/tnre.nim
tnre.nim(8, 11) Error: cannot open file: nre/init
```

I don't understand why

**Comment by haxscramper** [comment]
IMO Known issue skipping really makes it easier to read now

**Comment by canelhasmateus** [comment]
God's work
Tags == <3

**Comment by haxscramper** [comment]
> Tags == <3

Right, I forgot there were some duplicated tags, this is a TODO for the next PR as well.

**Comment by haxscramper** [comment]
ok finally green, ping @saem

**Review by saem — APPROVED** [review]
bors r+

cleaner than before

**Pull request merged**
