### PR TITLE
Reorganize test suite structure

### PR DESCRIPTION
**Pull request by haxscramper**
Document used test tags. Continue work on the test suite as proposed in the https://github.com/nim-works/nimskull/issues/41 -- sort toplevel test suite directories into more organized  places. Remove several one-off directories that contained  only single file  and nothing  else (such as  `tconcat` for instance).

This  PR/commit  is   only  concerned  with  reorganization   of  the  file arrangement in the test suite directory  -- no tests were edited aside from providing better comments/description/tags.

### CODE REVIEW

**Comment by haxscramper** [comment]
I'm not sure why the test suite fails *now* -- all errors reported in the "print failed tests" stage re marked as "known issue"

**Comment by saem** [comment]
It's going to take me time to review this, honestly this should be more carefully done in smaller pieces.

Each folder is a category and a bunch of them have special handling, a rename likely broke something, GitHub is struggling to render this on my phone so I can't review it in detail.

From what I've seen, `compile_detail` is a poor category name. Leave it as JS, at least then it's clear this about JS specifics and code gen. As for the other backends those aren't really compile details either. This will also negatively impact CI performance as parallelization is on a category basis.

I'll review some of the other category changes this weekend.

**Comment by haxscramper** [comment]
> This will also negatively impact CI performance as parallelization is on a category basis.

No change in CI time as far as I can tell. My prevous PR passed in 11/17 minutes respectively, this one takes 11/14 minutes to complete each batch.

**Comment by haxscramper** [comment]
> From what I've seen, `compile_detail` is a poor category name. Leave it as JS, at least then it's clear this about JS specifics and code gen.

Fixed

**Comment by haxscramper** [comment]
Partially superceded, will be done in smaller batches

**Pull request closed without merging**
