### PR TITLE
docs: build documentation for threading-related modules

### PR DESCRIPTION
**Pull request by Luyten-Orion**
## Summary
`kochdocs.nim`  in  `tools/koch/kochdocs.nim` ,  `docDefines`  now has 
`--threads:on`  to build docs for relevant threading API.

### CODE REVIEW

**Comment by zerbina** [comment]
Thank you for the PR! I've changed the title to make it a bit clearer what the user-relevant impact is.

**Comment by zerbina** [comment]
@Luyten-Orion: The compiler bug causing the `koch doc` failure should now be fixed (sorry that it took so long). Could you merge the `devel` branch into your PR?

**Comment by Luyten-Orion** [comment]
Sorry it took me so long, it's been done now

**Review by zerbina — APPROVED** [review]
All the threading-related API now shows up in the index, but the links in `index.html` are still broken, as both the `threads` and `channel_builtin` modules are *included* from `system.nim`, meaning that they need to be special-cased by doc generation. They once were, but this changed in #303.

In my opinion, this can be addressed separately, and I think the PR is good to go.

**Comment by saem** [comment]
/merge

I created an issue for the fix for the links themselves.

**Pull request merged**
