### PR TITLE
internal: add missing reports and clean-up

### PR DESCRIPTION
**Pull request by saem**
## Summary

added missing reports for the parser:
- template missing end close
- invalid expression
- invalid filter

Misc:
- created an enum for compiler verbosity
- removed `rparName`, doesn't seem used at all
- formatting fixes

### CODE REVIEW

**Comment by saem** [comment]
@haxscramper can you take a quick look at the `rparName` removal?

I don't think there is an issue, but just in case I didn't consider something.

**Comment by haxscramper** [comment]
No, no problems with `rparName` removal - IIRC it was created from parser "linter" diagnostics, but the whole thing wasn't used in the first place, apparently.

**Comment by saem** [comment]
hah, left some asserts in there.

**Comment by saem** [comment]
> No, no problems with `rparName` removal - IIRC it was created from parser "linter" diagnostics, but the whole thing wasn't used in the first place, apparently.

Thanks for looking it over -- yeah that was my conclusion too.

**Pull request merged**
