### PR TITLE
update the project roadmap diagram

### PR DESCRIPTION
**Pull request by haxscramper**
Replace the older project fixup diagram with a new, revised version that more accurately depicts current state of the project planning.

### CODE REVIEW

**Comment by saem** [comment]
- CPS comes much earlier, after untangling the C backend, fundamental runtime
- the JS backend needs a similar rewrite as the C backend, forced clarification native vs foreign semantics
- the above need to happen prior to C++ integration

**Comment by saem** [comment]
There is a dialect removal, which is a stream. Don't have to include it this time around. It's more about ripping out implementation. This would either be permanently removed, replaced with an equivalent on by default, or have indirect/multiple-things that are seen as a "replacement".

It's ok if we leave that stuff as version next.

**Comment by haxscramper** [comment]
> There is a dialect removal, which is a stream. Don't have to include it this time around.

There is a _"Clean up and improve implementation of the compiler, doc, stdlib. Remove dialects. Improve orthogonality."_ on the left side now.

**Pull request merged**
