### PR TITLE
lang: remove for loop and case statement macros

### PR DESCRIPTION
**Pull request by saem**
There are better ways to do these sorts of things.

### CODE REVIEW

**Comment by saem** [comment]
Bots r+

**Comment by SolitudeSF** [comment]
> There are better ways to do these sorts of things.

like what? is there a relevant discussion/motivation i can read?

**Comment by saem** [comment]
> > There are better ways to do these sorts of things.
> 
> like what? is there a relevant discussion/motivation i can read?

No, because there isn't a one to one replacement being considered. Considering the lack of any sort of _working_ interfaces starting with something like enumerable or iterable would be big leap forward. As for case, start making them less limited from the start. Performance issues get mitigated in many situations here and elsewhere with some partial evaluation.

**Comment by SolitudeSF** [comment]
i barely understand what are you trying to say here. im gonna have to ask more directly: why are for loop macros removed?

**Comment by saem** [comment]
> i barely understand what are you trying to say here. im gonna have to ask more directly: why are for loop macros removed?

Sorry, fat fingered the edit button at first.

I don't want this or many other features in the language. The approach is:

1. More obvious things should be done
2. See if those are insufficient
3. Discuss if this or some other approach is required

**Comment by SolitudeSF** [comment]
okay, now i get it.
just unfortunate to see the feature i like go.

**Comment by saem** [comment]
> okay, now i get it. just unfortunate to see the feature i like go.

It's useful to you, so it'd be helpful to capture some of the reasoning why here if you're up for sharing, thanks. https://github.com/nim-works/nimskull/discussions/289#discussioncomment-3344279

**Pull request merged**
