### PR TITLE
Text improvements

### PR DESCRIPTION
**Pull request by sschwarzer**
## Summary
* what changed and how?

    I changed a typo in the coding style document and made a few (I think) improvements in `readme.md` (see second commit message).

* why are we changing it?

    The changes are typo and grammar fixes and wording improvements.

Use as much or little of the changes as you wish. :-)

### CODE REVIEW

**Comment by haxscramper** [comment]
Sorry for delay in the response - there are no issues with this PR, so once you squash it, I think it can be merged. For squashing, see the relevant [section](https://nim-works.github.io/nimskull/contributing.html#the-cmdgit-stuff-pr-should-contain-a-single-commit) in the contributor's guide.

**Comment by sschwarzer** [comment]
Thanks for getting back. I saw the CI message about having a single commit when creating the PR, but I wasn't sure if I should squash the commits or a maintainer during the merge of the PR.

I just force-pushed my squashed commit, but before that I also rebased my branch on `devel` to be up to date, and now my PR appears to be listed with an additional commit that was made on `devel` by someone else. :-/ What should I do? Can this be fixed by me or a maintainer in this PR or should I create a new PR?

**Comment by alaviss** [comment]
> What should I do? Can this be fixed by me or a maintainer in this PR or should I create a new PR?

Update your local `devel` then `git rebase devel` again should solve the issue.

**Comment by sschwarzer** [comment]
@alaviss This seems to have worked now, thanks!

**Pull request merged**
