### PR TITLE
update Issue and PR templates

### PR DESCRIPTION
**Pull request by saem**
updates attempt to avoid noisy PRs and Issues, hopefully have some
helpful reminders.

issue templates:
- bug (spec) - for non-conformance, ambigutities, etc
- issue - where things aren't as expected, but it's outside the spec
- todo - things todo, meant for contributors

pr template:
- just some tips as to how to have a decent PR message
- and use the fixes trick

future considerations:
- we can configure behaviour bots for pre-canned messages, saving labour
- noted the previous point in in `.github/config.yml`
- specific issue templates can streamline labels and writing prompts
- github form language can let us collect structured info

### CODE REVIEW

**Review by disruptek — APPROVED** [review]
LGTM :+1:

**Comment by saem** [comment]
one more time

bors r+

**Review by alaviss — APPROVED** [review]
bors r+

**Pull request merged**
